feat(fetch secret): add secret fetching
rotationalio/whisper-ui pull request #9
Opened 2021-08-16 11:25 UTC by elysee15

<img width="1440" alt="Capture d’écran 2021-08-16 à 11 24 21" src="https://user-images.githubusercontent.com/54010836/129556282-2ed2f911-d0eb-49ff-af10-602cd8de962c.png">
<img width="1440" alt="Capture d’écran 2021-08-16 à 11 24 35" src="https://user-images.githubusercontent.com/54010836/129556309-9a0e5ac4-12d3-4137-9e77-34516baf9f9e.png">

2021-08-16 17:16 UTC, bbengfort requested changes
Well done, this is a big PR and you did a very good job handling the secret fetching flow, taking into account normal Secrets and Password-protected secrets. I think the password-protected flow is very well thought out; you handled multiple errors both from the back-end and the front-end and you thought about session storage so that delete worked without re-entering the password -- very well done! 

What would you think about adding a password hint? E.g. allowing the user to specify a hint int the create secret screen, then the 401 error would return the hint in the JSON body? This would require a change in the API as well and we could add it as another future feature if you thought it was an interesting idea. 

I've added a lot of comments to the PR; most of them are simply copy changes, which shouldn't require too much discussion. However, I did want us to rethink the use of 2 API calls in the password-protected deletion. I think this will have some far-ranging affects, including how the `FetchSecret` component works since it will require removing the secret from session storage instead of relying on it being overwritten or unneeded. Additionally, since this is so complex, it might be wise to have some accompanying tests for the session storage.

2021-08-16 17:16 UTC, bbengfort commented on src/components/Button.tsx
> +				{children ? children : isLoading ? <CircularProgress size={24} /> : label}
I like this loading button a lot - well done!

2021-08-16 17:16 UTC, bbengfort commented on src/components/SecretNotFound.tsx
> +				</Button>
Out of curiosity, why use a button here instead of a react router `Link`? It seems like an anchor tag styled as a button is semantically more correct for this.

2021-08-16 17:16 UTC, bbengfort commented on src/components/SecretNotFound.tsx
> +			textTransform: "uppercase"
Well done on translating the error message to make it look much nicer! The error messages that come back from the server will always be lower case and contain no punctuation (if they do, let me know - that's a bug). The reason is because the server may stack error messages with colons, e.g. `"error one due to: a different error"`.

Could we also use CSS text transform to add a `.` to the end of the sentence if we're going to upper-case the first letter?

2021-08-16 17:16 UTC, bbengfort commented on src/components/SecretNotFound.tsx
> +					<Typography>{message ? message : "This secret message has been perhaps destroyed"}</Typography>
Could we change the default message to `"No secret exists with the specified token."`? Hinting that the secret may have been destroyed may make users feel like we're leaking the fact that a secret may have existed at that token (which isn't true, but it's how they'll feel by the message).

2021-08-16 17:16 UTC, bbengfort commented on src/components/SecretPassword.tsx
> +			password: Yup.string().required("You must add the password")
Could we please change the validation text to `"A password is required to access this Secret"`?

2021-08-16 17:16 UTC, bbengfort commented on src/components/SecretPassword.tsx
> +				You type the wrong password. try again
Could we change this error text to `"Password not accepted, please try again."`. 

Also, what happens if the error is a 404 instead of a 401/403? E.g. the password was destroyed before they submitted their password?

2021-08-16 17:16 UTC, bbengfort commented on src/components/SecretPassword.tsx
> +				You should put the password before reading the secret message
Could we change this text to `"This Secret requires a password for access."`?

2021-08-16 17:16 UTC, bbengfort commented on src/components/SecretPassword.tsx
> +						label="Your secret password"
I like how the label changes from a placeholder to a label that is inset into the input border - very nice! Could we change the label text simply to `"Password"`?

2021-08-16 17:16 UTC, bbengfort commented on src/components/SecretPassword.tsx
> +						label="Submit password"
Could we make the button text `"Unlock Secret"` please?

2021-08-16 17:16 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +		if (window.confirm("Do you really want to delete the secret ?")) {
Could we update this text to `"Do you really want to destroy the secret?"`?

2021-08-16 17:16 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +				async (error: AxiosError) => {
You'll also have to handle the error response `404` - e.g. that the secret has already been destroyed. Right now if the secret has been destroyed, the isLoading button returns to "Destroy this Secret" but it looks like nothing has happened. In this case, the `404` case is also a success case, so the push back to `"/"` should happen again.

2021-08-16 17:16 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +							}
This is an interesting flow - submitting the deletion checking for a 401 and then trying again with the key. In the case of a password protected secret, this flow requires 2 API requests at minimum; however it does prevent sessionStorage access to the password if not required. 

However, what would be the cost of checking session storage for the key if it exists, and if it does, adding the Authorization header, otherwise leaving it alone? This would only require at most one API request, speeding up deletion and removes the use of server responses as a mechanism for controlling app state.

2021-08-16 17:16 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +					Your secret message
Can we update this to `"Secret"`?

2021-08-16 17:16 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +					</Typography>
Could we change this to:

```
<AlertTitle>Secret Expired</AlertTitle>
<Typography>
  This is the last time you will be able to access this Secret, it has been destroyed now that you've retrieved it.
</Typography>

2021-08-16 17:16 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +						readOnly
Excellent - I really like that the text is readonly but you can still copy and paste it!

2021-08-16 17:16 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +					Created: {dayjs(secret?.created).fromNow()}
Excellent! I like that this is a relative time from now, it makes the timestamp much more readable.

2021-08-16 17:16 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +					<Button
If the Secret has already been destroyed, could we hide this button? It seems to contradict the warning text above.

2021-08-16 17:16 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +					<Button label="Reply with another secret" variant="contained" color="primary" onClick={handleClick} />
I like the idea of replying to a secret with another secret :-) however in our context, perhaps "Create another Secret" is more appropriate? Also per my comment on the other  "back to create secret" Button text, this is another place where I thought a link styled as a button might be more appropriate.

2021-08-16 17:16 UTC, bbengfort commented on src/routes/index.tsx
> +		<Suspense fallback="loading...">
Nice use of `Suspense`! There are a couple of weird cases though:

- `/foo` goes to `CreateSecret` 
- `/secret/foo/bar` also goes to `CreateSecret` 

If we make the `"/"` Route exact also, what would happen in these cases, the fallback to loading? Should we make a ticket to create a 404, back to homepage screen?

2021-08-16 17:16 UTC, bbengfort commented on src/pages/FetchSecret.tsx
> +const FetchSecret: React.FC = () => {
I really like this component - well done on handling all of the different cases!

2021-08-16 17:16 UTC, bbengfort commented on src/services/ShowSecret.ts
> +				window.sessionStorage.setItem("__KEY__", encodedPassword);
This is one place where the `401` check in the destroy secret flow would have to be updated. If we check the `"__KEY__"` before submitting a destroy request, we would also have to remove it from session storage when we left the secret; otherwise we might have a passwordless secret that would attempt to be authorized, which might cause a bug. Additionally, since the key is global, we might have the case where the wrong password was used with the wrong token.

2021-08-16 17:16 UTC, bbengfort commented on src/utils/utils.ts
> +	return `${defaultEndpointPrefix()}/secret/${token}`;
For development, it would be much nicer if `generateSecretLink` returned `http://localhost:3000` instead of `https://whisper.rotational.dev/v1`. Also, we will have to partition the URLs, note that we have two choices for the API: `//api.whisper.rotational.dev/v1/secrets/:token` or `//whisper.rotational.dev/api/v1/secrets/:token` (the former being much nicer in my opinion, but the latter easier for CORS). But the front-end link should be `//whisper.rotational.dev/secret/:token`.

2021-08-16 17:16 UTC, bbengfort commented on src/utils/utils.ts
> +	return Buffer.from(str).toString("base64");
Nice!

2021-08-17 14:06 UTC, elysee15 commented on src/components/SecretNotFound.tsx
> +				</Button>
Yes, I agree with you

2021-08-17 14:11 UTC, elysee15 commented on src/routes/index.tsx
> +		<Suspense fallback="loading...">
Yes

2021-08-17 21:53 UTC, elysee15 commented on src/components/SecretNotFound.tsx
> +			textTransform: "uppercase"
Yes

2021-08-18 21:23 UTC, bbengfort reviewed
@elysee15 I started the review but it looks like there are still several comments that are unaddressed - I marked some of them with "bump" (e.g. nudge for attention) - is this helpful if GitHub is hiding them?

2021-08-18 21:23 UTC, bbengfort commented on src/components/SecretNotFound.tsx
> +					<Typography>{message ? `${message}.` : "No secret exists with the specified token."}</Typography>
Hehe, nice - probably a better solution than a `css:after`!

2021-08-18 21:23 UTC, bbengfort commented on src/components/SecretPassword.tsx
> +				You type the wrong password. try again
Bump @elysee15 - would you mind fixing this before we merge this PR? Also, thoughts on 404?

2021-08-18 21:23 UTC, bbengfort commented on src/components/SecretPassword.tsx
> +				You should put the password before reading the secret message
Bump

2021-08-18 21:23 UTC, bbengfort commented on src/components/SecretPassword.tsx
> +						label="Your secret password"
Bump

2021-08-18 21:23 UTC, bbengfort commented on src/components/SecretPassword.tsx
> +						label="Submit password"
Bump

2021-08-18 21:23 UTC, bbengfort commented on src/components/ShowSecret.tsx
> +		if (window.confirm("Do you really want to delete the secret ?")) {
Bump

2021-08-19 12:11 UTC, elysee15 commented on src/components/ShowSecret.tsx
> +					<Button
Alright

2021-08-20 14:31 UTC, bbengfort approved these changes
@elysee15 thanks for making those copy changes; I didn't do a full review since we're getting behind - but I'll get to #10 and #11 next -- would like to get this combined with the other repo so we can get deployment going!

2021-08-20 14:31 UTC, merged